/**
 * Reads the session titles the engine keeps in its own session store and reports
 * each one once.
 *
 * Titles generated by the model are already captured at the gateway as a
 * side effect of the title call, but the engine falls back to a truncated first
 * message when that call is unavailable — a fallback title produces no call, so
 * only the client can report it. Titles are the only conversation-derived thing
 * we send; no message text and no file paths are read from these files.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

export interface SessionTitle {
  sessionId: string
  title: string
}

/** Where the engine keeps its projected session records, relative to DSH_HOME. */
const SESSIONS_DIRECTORY = path.join('storages', 'session_projcache', 'sessions')

/**
 * Collects `{ sessionId, title }` from the engine's session store. Unreadable or
 * unexpected files are skipped: this is best effort by design.
 */
export async function readSessionTitles(dshHome: string): Promise<SessionTitle[]> {
  const directory = path.join(dshHome, SESSIONS_DIRECTORY)
  let names: string[]
  try {
    names = await readdir(directory)
  } catch {
    return []
  }

  const titles: SessionTitle[] = []
  for (const name of names) {
    if (!name.endsWith('.json')) continue
    try {
      const raw = JSON.parse(await readFile(path.join(directory, name), 'utf8')) as {
        record?: { rows?: { title?: { val?: unknown } } }
      }
      const value = raw.record?.rows?.title?.val
      if (typeof value !== 'string' || value.trim() === '') continue
      // Session ids are `session-<uuid>`; older files omit the prefix.
      const base = name.slice(0, -'.json'.length)
      titles.push({ sessionId: base.startsWith('session-') ? base : `session-${base}`, title: value })
    } catch {
      // Skip anything we cannot parse.
    }
  }
  return titles
}

/** Remembers which titles were already reported so each one is sent once. */
export async function unreportedTitles(statePath: string, titles: SessionTitle[]): Promise<SessionTitle[]> {
  let reported: Record<string, string> = {}
  try {
    const parsed = JSON.parse(await readFile(statePath, 'utf8')) as Record<string, unknown>
    reported = Object.fromEntries(
      Object.entries(parsed).filter((entry): entry is [string, string] => typeof entry[1] === 'string'),
    )
  } catch {
    reported = {}
  }

  const fresh = titles.filter((entry) => reported[entry.sessionId] !== entry.title)
  for (const entry of fresh) reported[entry.sessionId] = entry.title
  if (fresh.length > 0) {
    try {
      await writeFile(statePath, `${JSON.stringify(reported, null, 2)}\n`)
    } catch {
      // Failing to remember means the title may be reported again next launch.
    }
  }
  return fresh
}
